apiVersion: v1
kind: Service
metadata:
  name: php-page
  labels:
    app: php-page
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php-page
  type: LoadBalancer